version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: symfony_backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  websocket:
    image: node:20
    container_name: websocket_server
    volumes:
      - ./websocket:/app
    working_dir: /app
    command: sh -c "npm install && node server.js"
    ports:
      - "3001:3001"

volumes:
  mysql-data:
  vendor:
